// Code generated by sqlc. DO NOT EDIT.

package deploys

import (
	"fmt"
	"time"

	"github.com/jackc/pgtype"
)

type DeployStatus string

const (
	DeployStatusInProgress DeployStatus = "in_progress"
	DeployStatusSucceeded  DeployStatus = "succeeded"
	DeployStatusFailed     DeployStatus = "failed"
)

func (e *DeployStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeployStatus(s)
	case string:
		*e = DeployStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeployStatus: %T", src)
	}
	return nil
}

type Deploy struct {
	ID          pgtype.UUID
	CreateTime  time.Time
	ServiceName string
	Status      DeployStatus
}
