// Code generated by sqlc. DO NOT EDIT.

package deploys

import (
	"context"

	"github.com/jackc/pgtype"
)

type Querier interface {
	AddDeploy(ctx context.Context, arg AddDeployParams) (Deploy, error)
	GetDeploy(ctx context.Context, id pgtype.UUID) (Deploy, error)
}

var _ Querier = (*Queries)(nil)
