// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: proto/deploys.proto

package deploys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployStatus int32

const (
	DeployStatus_IN_PROGRESS DeployStatus = 0
	DeployStatus_SUCCEEDED   DeployStatus = 1
	DeployStatus_FAILED      DeployStatus = 2
)

// Enum value maps for DeployStatus.
var (
	DeployStatus_name = map[int32]string{
		0: "IN_PROGRESS",
		1: "SUCCEEDED",
		2: "FAILED",
	}
	DeployStatus_value = map[string]int32{
		"IN_PROGRESS": 0,
		"SUCCEEDED":   1,
		"FAILED":      2,
	}
)

func (x DeployStatus) Enum() *DeployStatus {
	p := new(DeployStatus)
	*p = x
	return p
}

func (x DeployStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_deploys_proto_enumTypes[0].Descriptor()
}

func (DeployStatus) Type() protoreflect.EnumType {
	return &file_proto_deploys_proto_enumTypes[0]
}

func (x DeployStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployStatus.Descriptor instead.
func (DeployStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_deploys_proto_rawDescGZIP(), []int{0}
}

type Deploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Status      DeployStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=deploys.DeployStatus" json:"status,omitempty"`
}

func (x *Deploy) Reset() {
	*x = Deploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deploy) ProtoMessage() {}

func (x *Deploy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deploy.ProtoReflect.Descriptor instead.
func (*Deploy) Descriptor() ([]byte, []int) {
	return file_proto_deploys_proto_rawDescGZIP(), []int{0}
}

func (x *Deploy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deploy) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Deploy) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Deploy) GetStatus() DeployStatus {
	if x != nil {
		return x.Status
	}
	return DeployStatus_IN_PROGRESS
}

type AddDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *AddDeployRequest) Reset() {
	*x = AddDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeployRequest) ProtoMessage() {}

func (x *AddDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeployRequest.ProtoReflect.Descriptor instead.
func (*AddDeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_deploys_proto_rawDescGZIP(), []int{1}
}

func (x *AddDeployRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDeployRequest) Reset() {
	*x = GetDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeployRequest) ProtoMessage() {}

func (x *GetDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeployRequest.ProtoReflect.Descriptor instead.
func (*GetDeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_deploys_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeployRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_deploys_proto protoreflect.FileDescriptor

var file_proto_deploys_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x73, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a,
	0x06, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x73, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x35, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x2a, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x32, 0x85, 0x01,
	0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x19, 0x2e, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x73, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x19, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x73, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x61, 0x6c, 0x61, 0x6d, 0x61, 0x74, 0x69, 0x2f, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x64, 0x6f, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_deploys_proto_rawDescOnce sync.Once
	file_proto_deploys_proto_rawDescData = file_proto_deploys_proto_rawDesc
)

func file_proto_deploys_proto_rawDescGZIP() []byte {
	file_proto_deploys_proto_rawDescOnce.Do(func() {
		file_proto_deploys_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_deploys_proto_rawDescData)
	})
	return file_proto_deploys_proto_rawDescData
}

var file_proto_deploys_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_deploys_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_deploys_proto_goTypes = []interface{}{
	(DeployStatus)(0),             // 0: deploys.DeployStatus
	(*Deploy)(nil),                // 1: deploys.Deploy
	(*AddDeployRequest)(nil),      // 2: deploys.AddDeployRequest
	(*GetDeployRequest)(nil),      // 3: deploys.GetDeployRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_deploys_proto_depIdxs = []int32{
	4, // 0: deploys.Deploy.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: deploys.Deploy.status:type_name -> deploys.DeployStatus
	2, // 2: deploys.DeployService.AddDeploy:input_type -> deploys.AddDeployRequest
	3, // 3: deploys.DeployService.GetDeploy:input_type -> deploys.GetDeployRequest
	1, // 4: deploys.DeployService.AddDeploy:output_type -> deploys.Deploy
	1, // 5: deploys.DeployService.GetDeploy:output_type -> deploys.Deploy
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_deploys_proto_init() }
func file_proto_deploys_proto_init() {
	if File_proto_deploys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_deploys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deploys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deploys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_deploys_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deploys_proto_goTypes,
		DependencyIndexes: file_proto_deploys_proto_depIdxs,
		EnumInfos:         file_proto_deploys_proto_enumTypes,
		MessageInfos:      file_proto_deploys_proto_msgTypes,
	}.Build()
	File_proto_deploys_proto = out.File
	file_proto_deploys_proto_rawDesc = nil
	file_proto_deploys_proto_goTypes = nil
	file_proto_deploys_proto_depIdxs = nil
}
